name: kuberlab
description: Web-based UI for managing Kubernetes clusters and applications.
version: 1.0.0
home: https://kuberlab.io/
keywords:
 - kuberlab
 - kubernetes
 - ui
sources:
  - https://github.com/kubernetes/dashboard
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
