apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: cirrus-es-data
  namespace: kuberlab
spec:
  clusterIP: None
  ports:
    - port: 9300
      targetPort: 9300
  selector:
    component: cirrus-es
    type: data
