apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: kuberlab
  labels:
    app: kuberlab
    component: postgresql
type: Opaque
data:
  postgres-password:  "amRqY25ETiEzaW5Oa1otIzg="